import { hexToBytes } from "@noble/hashes/utils.js";
import { encrypt } from "nostr-tools/nip04";
import { finalizeEvent, type EventTemplate } from "nostr-tools/pure";
import { NWCWalletRequest } from "nostr-tools/kinds";
import { SimplePool } from "nostr-tools/pool";

const PUBLISH_TIMEOUT_MS = 8000;

export type NwcPushResult = { sent: true } | { sent: false; error: string };

// nostr-tools@2.25.2 ships lib/esm/nip47.js but its package.json "exports"
// map omits the "./nip47" subpath (confirmed against the published npm
// tarball, not just this install) — importing it 404s under Node/Turbopack's
// strict exports resolution. nip47.ts itself is a thin wrapper around
// nip04's encrypt + pure's finalizeEvent + the NWCWalletRequest kind, all of
// which *are* exported, so we reimplement the same two functions from those
// building blocks instead of patching or waiting on upstream.
type NwcConnection = { pubkey: string; relay: string; relays: string[]; secret: string };

function parseConnectionString(connectionString: string): NwcConnection {
  const { host, pathname, searchParams } = new URL(connectionString);
  const pubkey = pathname || host;
  const relays = searchParams.getAll("relay");
  const secret = searchParams.get("secret");
  if (!pubkey || relays.length === 0 || !secret) {
    throw new Error("invalid connection string");
  }
  return { pubkey, relay: relays[0], relays, secret };
}

function makeNwcRequestEvent(pubkey: string, secretKey: Uint8Array, invoice: string) {
  const content = { method: "pay_invoice", params: { invoice } };
  const encryptedContent = encrypt(secretKey, pubkey, JSON.stringify(content));
  const eventTemplate: EventTemplate = {
    kind: NWCWalletRequest,
    created_at: Math.round(Date.now() / 1000),
    content: encryptedContent,
    tags: [["p", pubkey]],
  };
  return finalizeEvent(eventTemplate, secretKey);
}

/**
 * Best-effort: asks the agent's own NWC-connected wallet to pay the given
 * invoice, by publishing a NIP-47 `pay_invoice` request event to its relay.
 *
 * This does NOT wait for (or trust) the wallet's response — the invoice
 * itself was already generated by our own LNbits node (see
 * lib/payments/lnbits.ts), so the *authoritative* payment confirmation
 * stays exactly as it was before this existed: getOrderStatus() polling
 * LNbits directly. This function only exists to save the caller the step
 * of paying the invoice through some other channel; if the relay is
 * unreachable, the wallet is offline, or the connection string is bad,
 * the order simply stays pending_payment — the same failure mode as if
 * the agent had been handed the invoice and never paid it. Nothing about
 * escrow, verification, or spend-cap enforcement depends on this succeeding.
 */
export async function requestWalletPayment(connectionString: string, invoice: string): Promise<NwcPushResult> {
  let conn: ReturnType<typeof parseConnectionString>;
  try {
    conn = parseConnectionString(connectionString);
  } catch {
    return { sent: false, error: "invalid agent_wallet_connection — expected a nostr+walletconnect:// URI" };
  }

  const pool = new SimplePool();
  try {
    const event = await makeNwcRequestEvent(conn.pubkey, hexToBytes(conn.secret), invoice);

    const timeout = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("timed out reaching the wallet's relay")), PUBLISH_TIMEOUT_MS)
    );
    // Any one relay accepting the event is enough — NIP-47 wallets commonly
    // advertise multiple relays for redundancy.
    await Promise.race([Promise.any(pool.publish(conn.relays, event)), timeout]);
    return { sent: true };
  } catch (err) {
    const message = err instanceof AggregateError ? "no relay accepted the payment request" : err instanceof Error ? err.message : "failed to reach wallet";
    return { sent: false, error: message };
  } finally {
    pool.close(conn.relays);
  }
}
